import { findTable, primaryKeyColumns, relSentence, type Diagram } from "@/lib/model";
import { resolveForeignKeys } from "./fk";

/** DBML names: bare when simple, otherwise double-quoted. */
function dbmlName(name: string): string {
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(name) ? name : `"${name.replace(/"/g, '\\"')}"`;
}

function dbmlType(type: string): string {
  const t = type.trim() || "varchar";
  return /^[A-Za-z_][A-Za-z0-9_]*(\([0-9, ]*\))?$/.test(t) ? t.replace(/\s+/g, "") : `"${t}"`;
}

function dbmlString(s: string): string {
  if (/[\r\n]/.test(s)) return `'''${s.replace(/'''/g, "\\'''")}'''`;
  return `'${s.replace(/\\/g, "\\\\").replace(/'/g, "\\'")}'`;
}

/** Default value: numbers, booleans, null and quoted strings as-is; anything else is an expression. */
function dbmlDefault(v: string): string {
  const s = v.trim();
  if (/^-?\d+(\.\d+)?$/.test(s) || /^(true|false|null)$/i.test(s)) return s.toLowerCase();
  const str = /^'((?:[^']|'')*)'$/.exec(s);
  if (str) return dbmlString(str[1].replace(/''/g, "'"));
  return "`" + s.replace(/`/g, "") + "`";
}

const ACTION: Record<string, string> = {
  CASCADE: "cascade",
  RESTRICT: "restrict",
  "SET NULL": "set null",
  "SET DEFAULT": "set default",
};

/** DBML (dbdiagram.io) source. */
export function toDbml(d: Diagram): string {
  const out: string[] = [];
  out.push(`// ${d.name.replace(/[\r\n]+/g, " ") || "Untitled diagram"}`);
  out.push("// Generated by ERD Studio");

  for (const t of d.tables) {
    out.push("", `Table ${dbmlName(t.name || "table")} {`);
    const pk = primaryKeyColumns(t);
    for (const c of t.columns) {
      const settings: string[] = [];
      if (c.pk && pk.length === 1) settings.push("pk");
      if (!c.nullable || c.pk) settings.push("not null");
      if (c.unique && !(c.pk && pk.length === 1)) settings.push("unique");
      if (c.defaultValue.trim()) settings.push(`default: ${dbmlDefault(c.defaultValue)}`);
      if (c.note.trim()) settings.push(`note: ${dbmlString(c.note.trim())}`);
      const s = settings.length ? ` [${settings.join(", ")}]` : "";
      out.push(`  ${dbmlName(c.name || "column")} ${dbmlType(c.type)}${s}`);
    }
    if (pk.length > 1) {
      out.push(
        "",
        "  indexes {",
        `    (${pk.map((c) => dbmlName(c.name)).join(", ")}) [pk]`,
        "  }",
      );
    }
    if (t.note.trim()) out.push("", `  Note: ${dbmlString(t.note.trim())}`);
    out.push("}");
  }

  const { fks, manyToMany, unresolved } = resolveForeignKeys(d);
  const refs: string[] = [];
  const cols = (names: string[]) =>
    names.length === 1 ? dbmlName(names[0]) : `(${names.map(dbmlName).join(", ")})`;
  for (const fk of fks) {
    const actions: string[] = [];
    if (ACTION[fk.onDelete]) actions.push(`delete: ${ACTION[fk.onDelete]}`);
    if (ACTION[fk.onUpdate]) actions.push(`update: ${ACTION[fk.onUpdate]}`);
    const op = fk.oneToOne ? "-" : "<";
    refs.push(
      `Ref ${fk.name}: ${dbmlName(fk.parent.name)}.${cols(fk.parentCols.map((c) => c.name))} ${op} ` +
        `${dbmlName(fk.child.name)}.${cols(fk.childCols.map((c) => c.name))}` +
        (actions.length ? ` [${actions.join(", ")}]` : ""),
    );
  }
  for (const r of manyToMany) {
    const a = findTable(d, r.from)!;
    const b = findTable(d, r.to)!;
    const pa = primaryKeyColumns(a);
    const pb = primaryKeyColumns(b);
    if (pa.length === 1 && pb.length === 1) {
      refs.push(
        `Ref: ${dbmlName(a.name)}.${dbmlName(pa[0].name)} <> ${dbmlName(b.name)}.${dbmlName(pb[0].name)}`,
      );
    } else {
      refs.push(`// ${relSentence(d, r)}: many-to-many needs a single-column key on each side`);
    }
  }
  for (const { rel } of unresolved) {
    refs.push(`// ${relSentence(d, rel)}: no foreign-key column chosen yet`);
  }
  if (refs.length) out.push("", ...refs);
  return out.join("\n") + "\n";
}
