import { describe, expect, it } from "vitest";
import {
  makeColumn,
  makeRelationship,
  makeTable,
  sampleDiagram,
  type Diagram,
  type Table,
} from "@/lib/model";
import { mermaidConnector, toMermaid } from "./mermaid";
import { toDbml } from "./dbml";

function diagram(tables: Table[], rels: Diagram["rels"] = []): Diagram {
  return { version: 2, name: "Test", tables, rels, view: null, updatedAt: 0 };
}

describe("toMermaid", () => {
  it("renders the sample diagram", () => {
    const d = sampleDiagram();
    d.tables[0].columns[2].note = 'Login "id"';
    expect(toMermaid(d)).toMatchInlineSnapshot(`
      "erDiagram
          customers {
              INT customer_id PK
              VARCHAR(100) full_name
              VARCHAR(255) email UK "Login 'id'"
              VARCHAR(20) phone_1
              VARCHAR(20) phone_2
          }
          orders {
              INT order_id PK
              INT customer_id FK
              VARCHAR(255) customer_email
              DATE order_date
              VARCHAR(10) postcode
              VARCHAR(60) city
          }
          products {
              INT product_id PK
              VARCHAR(100) name
              DECIMAL(10-2) price
          }
          customers ||--o{ orders : places
          orders }|--o{ products : contains
      "
    `);
  });

  it("picks crow's-foot markers from cardinality and optionality", () => {
    const r = makeRelationship("a", "b");
    expect(mermaidConnector({ ...r, type: "1:N", fromOptional: false, toOptional: true })).toBe(
      "||--o{",
    );
    expect(mermaidConnector({ ...r, type: "1:N", fromOptional: true, toOptional: false })).toBe(
      "|o--|{",
    );
    expect(mermaidConnector({ ...r, type: "1:1", fromOptional: false, toOptional: true })).toBe(
      "||--o|",
    );
    expect(mermaidConnector({ ...r, type: "1:1", fromOptional: false, toOptional: false })).toBe(
      "||--||",
    );
    expect(mermaidConnector({ ...r, type: "N:M", fromOptional: true, toOptional: true })).toBe(
      "}o--o{",
    );
  });

  it("sanitises names and types Mermaid can't take", () => {
    const a = makeTable("order items", 0, 0, {
      columns: [
        makeColumn("unit price", "DECIMAL(10, 2)"),
        makeColumn("2nd", "DOUBLE PRECISION"),
        makeColumn("x", ""),
      ],
    });
    const b = makeTable("order-items", 0, 0);
    const c = makeTable("order_items", 0, 0);
    const out = toMermaid(
      diagram([a, b, c], [makeRelationship(a.id, b.id, { label: "belongs to" })]),
    );
    expect(out).toContain("    order_items {");
    expect(out).toContain("        DECIMAL(10-2) unit_price");
    expect(out).toContain("        DOUBLE_PRECISION _2nd");
    expect(out).toContain("        unknown x");
    expect(out).toContain("    order-items {");
    expect(out).toContain("    order_items_2 {");
    expect(out).toContain('    order_items ||--o{ order-items : "belongs to"');
  });
});

describe("toDbml", () => {
  it("renders the sample diagram", () => {
    const d = sampleDiagram();
    d.tables[0].note = "People who buy";
    d.tables[1].columns[3].defaultValue = "now()";
    expect(toDbml(d)).toMatchInlineSnapshot(`
      "// Shop example
      // Generated by ERD Studio

      Table customers {
        customer_id INT [pk, not null]
        full_name VARCHAR(100) [not null]
        email VARCHAR(255) [not null, unique]
        phone_1 VARCHAR(20)
        phone_2 VARCHAR(20)

        Note: 'People who buy'
      }

      Table orders {
        order_id INT [pk, not null]
        customer_id INT [not null]
        customer_email VARCHAR(255) [not null]
        order_date DATE [not null, default: \`now()\`]
        postcode VARCHAR(10) [not null]
        city VARCHAR(60) [not null]
      }

      Table products {
        product_id INT [pk, not null]
        name VARCHAR(100) [not null]
        price DECIMAL(10,2) [not null]
      }

      Ref fk_orders_customer_id: customers.customer_id < orders.customer_id
      Ref: orders.order_id <> products.product_id
      "
    `);
  });

  it("writes composite keys, defaults, notes and referential actions", () => {
    const orders = makeTable("orders", 0, 0, {
      columns: [makeColumn("id", "INT", { pk: true })],
    });
    const lines = makeTable("order lines", 0, 0, {
      columns: [
        makeColumn("order_id", "INT", { pk: true }),
        makeColumn("line_no", "INT", { pk: true }),
        makeColumn("qty", "INT", { defaultValue: "1" }),
        makeColumn("status", "VARCHAR(10)", { defaultValue: "'new'", note: "it's new" }),
        makeColumn("amount", "DOUBLE PRECISION", { nullable: true }),
      ],
    });
    const passports = makeTable("passports", 0, 0, {
      columns: [makeColumn("id", "INT", { pk: true }), makeColumn("order_id", "INT")],
    });
    const out = toDbml(
      diagram(
        [orders, lines, passports],
        [
          makeRelationship(orders.id, lines.id, {
            fromCol: orders.columns[0].id,
            toCol: lines.columns[0].id,
            onDelete: "CASCADE",
            onUpdate: "SET NULL",
          }),
          makeRelationship(orders.id, passports.id, {
            fromCol: orders.columns[0].id,
            toCol: passports.columns[1].id,
            type: "1:1",
          }),
          makeRelationship(lines.id, passports.id),
        ],
      ),
    );
    expect(out).toContain('Table "order lines" {');
    expect(out).toContain("  order_id INT [not null]");
    expect(out).toContain("  qty INT [not null, default: 1]");
    expect(out).toContain("  status VARCHAR(10) [not null, default: 'new', note: 'it\\'s new']");
    expect(out).toContain('  amount "DOUBLE PRECISION"');
    expect(out).toContain("  indexes {\n    (order_id, line_no) [pk]\n  }");
    expect(out).toContain(
      'Ref fk_order_lines_order_id: orders.id < "order lines".order_id [delete: cascade, update: set null]',
    );
    expect(out).toContain("Ref fk_passports_order_id: orders.id - passports.order_id");
    expect(out).toContain(
      "// order lines (one) has passports (many): no foreign-key column chosen yet",
    );
  });
});
