import { describe, expect, it } from "vitest";
import {
  makeColumn,
  makeRelationship,
  makeTable,
  sampleDiagram,
  type Diagram,
  type Table,
} from "@/lib/model";
import { toSql } from "./export";
import { mapType, quoteIdent } from "./dialects";

function diagram(tables: Table[], rels: Diagram["rels"] = [], name = "Test"): Diagram {
  return { version: 2, name, tables, rels, view: null, updatedAt: 0 };
}

describe("toSql — sample diagram per dialect", () => {
  it("postgres", () => {
    expect(toSql(sampleDiagram(), "postgres")).toMatchInlineSnapshot(`
      "-- Shop example
      -- Generated by ERD Studio for PostgreSQL

      CREATE TABLE customers (
        customer_id INT          NOT NULL,
        full_name   VARCHAR(100) NOT NULL,
        email       VARCHAR(255) NOT NULL UNIQUE,
        phone_1     VARCHAR(20),
        phone_2     VARCHAR(20),
        PRIMARY KEY (customer_id)
      );

      CREATE TABLE orders (
        order_id       INT          NOT NULL,
        customer_id    INT          NOT NULL,
        customer_email VARCHAR(255) NOT NULL,
        order_date     DATE         NOT NULL,
        postcode       VARCHAR(10)  NOT NULL,
        city           VARCHAR(60)  NOT NULL,
        PRIMARY KEY (order_id),
        CONSTRAINT fk_orders_customer_id FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
      );

      CREATE TABLE products (
        product_id INT           NOT NULL,
        name       VARCHAR(100)  NOT NULL,
        price      DECIMAL(10,2) NOT NULL,
        PRIMARY KEY (product_id)
      );

      -- Many-to-many: orders (many) contains products (many). Add a junction table such as
      --   orders_products with a foreign key to each side.
      "
    `);
  });
  it("mysql", () => {
    expect(toSql(sampleDiagram(), "mysql")).toMatchInlineSnapshot(`
      "-- Shop example
      -- Generated by ERD Studio for MySQL

      CREATE TABLE customers (
        customer_id INT          NOT NULL,
        full_name   VARCHAR(100) NOT NULL,
        email       VARCHAR(255) NOT NULL UNIQUE,
        phone_1     VARCHAR(20),
        phone_2     VARCHAR(20),
        PRIMARY KEY (customer_id)
      );

      CREATE TABLE orders (
        order_id       INT          NOT NULL,
        customer_id    INT          NOT NULL,
        customer_email VARCHAR(255) NOT NULL,
        order_date     DATE         NOT NULL,
        postcode       VARCHAR(10)  NOT NULL,
        city           VARCHAR(60)  NOT NULL,
        PRIMARY KEY (order_id),
        CONSTRAINT fk_orders_customer_id FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
      );

      CREATE TABLE products (
        product_id INT           NOT NULL,
        name       VARCHAR(100)  NOT NULL,
        price      DECIMAL(10,2) NOT NULL,
        PRIMARY KEY (product_id)
      );

      -- Many-to-many: orders (many) contains products (many). Add a junction table such as
      --   orders_products with a foreign key to each side.
      "
    `);
  });
  it("sqlite", () => {
    expect(toSql(sampleDiagram(), "sqlite")).toMatchInlineSnapshot(`
      "-- Shop example
      -- Generated by ERD Studio for SQLite

      PRAGMA foreign_keys = ON;

      CREATE TABLE customers (
        customer_id INT          NOT NULL,
        full_name   VARCHAR(100) NOT NULL,
        email       VARCHAR(255) NOT NULL UNIQUE,
        phone_1     VARCHAR(20),
        phone_2     VARCHAR(20),
        PRIMARY KEY (customer_id)
      );

      CREATE TABLE orders (
        order_id       INT          NOT NULL,
        customer_id    INT          NOT NULL,
        customer_email VARCHAR(255) NOT NULL,
        order_date     DATE         NOT NULL,
        postcode       VARCHAR(10)  NOT NULL,
        city           VARCHAR(60)  NOT NULL,
        PRIMARY KEY (order_id),
        CONSTRAINT fk_orders_customer_id FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
      );

      CREATE TABLE products (
        product_id INT           NOT NULL,
        name       VARCHAR(100)  NOT NULL,
        price      DECIMAL(10,2) NOT NULL,
        PRIMARY KEY (product_id)
      );

      -- Many-to-many: orders (many) contains products (many). Add a junction table such as
      --   orders_products with a foreign key to each side.
      "
    `);
  });
  it("sqlserver", () => {
    expect(toSql(sampleDiagram(), "sqlserver")).toMatchInlineSnapshot(`
      "-- Shop example
      -- Generated by ERD Studio for SQL Server

      CREATE TABLE customers (
        customer_id INT          NOT NULL,
        full_name   VARCHAR(100) NOT NULL,
        email       VARCHAR(255) NOT NULL UNIQUE,
        phone_1     VARCHAR(20)  NULL,
        phone_2     VARCHAR(20)  NULL,
        PRIMARY KEY (customer_id)
      );

      CREATE TABLE orders (
        order_id       INT          NOT NULL,
        customer_id    INT          NOT NULL,
        customer_email VARCHAR(255) NOT NULL,
        order_date     DATE         NOT NULL,
        postcode       VARCHAR(10)  NOT NULL,
        city           VARCHAR(60)  NOT NULL,
        PRIMARY KEY (order_id),
        CONSTRAINT fk_orders_customer_id FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
      );

      CREATE TABLE products (
        product_id INT           NOT NULL,
        name       VARCHAR(100)  NOT NULL,
        price      DECIMAL(10,2) NOT NULL,
        PRIMARY KEY (product_id)
      );

      -- Many-to-many: orders (many) contains products (many). Add a junction table such as
      --   orders_products with a foreign key to each side.
      "
    `);
  });
  it("is deterministic", () => {
    const d = sampleDiagram();
    expect(toSql(d, "postgres")).toBe(toSql(d, "postgres"));
  });
});

describe("quoteIdent", () => {
  it("leaves plain names alone", () => {
    expect(quoteIdent("customer_id", "postgres")).toBe("customer_id");
    expect(quoteIdent("CustomerId", "mysql")).toBe("CustomerId");
  });
  it("quotes reserved words per dialect", () => {
    expect(quoteIdent("order", "postgres")).toBe('"order"');
    expect(quoteIdent("user", "mysql")).toBe("`user`");
    expect(quoteIdent("Key", "sqlserver")).toBe("[Key]");
    expect(quoteIdent("group", "sqlite")).toBe('"group"');
  });
  it("quotes mixed case only in postgres", () => {
    expect(quoteIdent("OrderItems", "postgres")).toBe('"OrderItems"');
    expect(quoteIdent("OrderItems", "sqlserver")).toBe("OrderItems");
  });
  it("quotes spaces and escapes the quote character", () => {
    expect(quoteIdent("line items", "postgres")).toBe('"line items"');
    expect(quoteIdent('a"b', "postgres")).toBe('"a""b"');
    expect(quoteIdent("a`b", "mysql")).toBe("`a``b`");
    expect(quoteIdent("a]b", "sqlserver")).toBe("[a]]b]");
  });
});

describe("mapType", () => {
  it("maps SERIAL", () => {
    expect(mapType("SERIAL", "postgres").type).toBe("SERIAL");
    expect(mapType("SERIAL", "mysql").type).toBe("INT AUTO_INCREMENT");
    expect(mapType("serial", "sqlite")).toEqual({ type: "INTEGER", autoIncrement: true });
    expect(mapType("BIGSERIAL", "sqlserver").type).toBe("BIGINT IDENTITY(1,1)");
  });
  it("maps booleans, UUIDs, text and dates", () => {
    expect(mapType("BOOLEAN", "sqlserver").type).toBe("BIT");
    expect(mapType("BOOLEAN", "mysql").type).toBe("BOOLEAN");
    expect(mapType("UUID", "mysql").type).toBe("CHAR(36)");
    expect(mapType("UUID", "sqlite").type).toBe("TEXT");
    expect(mapType("uuid", "sqlserver").type).toBe("UNIQUEIDENTIFIER");
    expect(mapType("TEXT", "sqlserver").type).toBe("NVARCHAR(MAX)");
    expect(mapType("DATETIME", "postgres").type).toBe("TIMESTAMP");
    expect(mapType("TIMESTAMP", "sqlserver").type).toBe("DATETIME2");
    expect(mapType("TIMESTAMP WITH TIME ZONE", "sqlserver").type).toBe("DATETIMEOFFSET");
    expect(mapType("NVARCHAR(MAX)", "postgres").type).toBe("TEXT");
    expect(mapType("TINYINT(1)", "postgres").type).toBe("SMALLINT");
  });
  it("keeps unknown types as written", () => {
    expect(mapType("varchar(20)", "postgres").type).toBe("varchar(20)");
    expect(mapType("DECIMAL(10, 2)", "mysql").type).toBe("DECIMAL(10, 2)");
    expect(mapType("INT UNSIGNED", "mysql").type).toBe("INT UNSIGNED");
    expect(mapType("INT UNSIGNED", "postgres").type).toBe("INT");
  });
  it("handles arrays", () => {
    expect(mapType("TEXT[]", "postgres").type).toBe("TEXT[]");
    expect(mapType("TEXT[]", "mysql")).toEqual({ type: "JSON", comment: "was TEXT[]" });
  });
  it("defaults an empty type with a TODO", () => {
    expect(mapType("", "postgres")).toEqual({
      type: "VARCHAR(255)",
      comment: "TODO: choose a data type",
    });
  });
});

describe("toSql — details", () => {
  it("quotes names that need it, in constraints too", () => {
    const user = makeTable("User", 0, 0, {
      columns: [makeColumn("id", "INT", { pk: true }), makeColumn("order", "INT")],
    });
    const items = makeTable("line items", 0, 0, {
      columns: [makeColumn("id", "INT", { pk: true }), makeColumn("User Id", "INT")],
    });
    const d = diagram(
      [user, items],
      [
        makeRelationship(user.id, items.id, {
          fromCol: user.columns[0].id,
          toCol: items.columns[1].id,
        }),
      ],
    );
    const sql = toSql(d, "postgres");
    expect(sql).toContain('CREATE TABLE "User" (');
    expect(sql).toContain('  "order" INT NOT NULL');
    expect(sql).toContain(
      'CONSTRAINT fk_line_items_user_id FOREIGN KEY ("User Id") REFERENCES "User" (id)',
    );
    expect(toSql(d, "sqlserver")).toContain("CREATE TABLE [line items] (");
    expect(toSql(d, "mysql")).toContain("CREATE TABLE `User` (");
  });

  it("emits composite primary keys and merges composite foreign keys", () => {
    const orders = makeTable("orders", 0, 0, {
      columns: [makeColumn("id", "INT", { pk: true })],
    });
    const lines = makeTable("order_lines", 0, 0, {
      columns: [
        makeColumn("order_id", "INT", { pk: true }),
        makeColumn("line_no", "INT", { pk: true }),
      ],
    });
    const notes = makeTable("line_notes", 0, 0, {
      columns: [
        makeColumn("id", "INT", { pk: true }),
        makeColumn("line_no", "INT"),
        makeColumn("order_id", "INT"),
      ],
    });
    const d = diagram(
      [notes, lines, orders],
      [
        makeRelationship(orders.id, lines.id, {
          fromCol: orders.columns[0].id,
          toCol: lines.columns[0].id,
          onDelete: "CASCADE",
        }),
        makeRelationship(lines.id, notes.id, {
          fromCol: lines.columns[1].id,
          toCol: notes.columns[1].id,
          onDelete: "CASCADE",
          onUpdate: "SET NULL",
        }),
        makeRelationship(lines.id, notes.id, {
          fromCol: lines.columns[0].id,
          toCol: notes.columns[2].id,
        }),
      ],
    );
    const sql = toSql(d, "postgres");
    expect(sql).toContain("PRIMARY KEY (order_id, line_no)");
    expect(sql).toContain(
      "CONSTRAINT fk_line_notes_order_id_line_no FOREIGN KEY (order_id, line_no) " +
        "REFERENCES order_lines (order_id, line_no) ON DELETE CASCADE ON UPDATE SET NULL",
    );
    // Dependency order: orders, then order_lines, then line_notes.
    const pos = (t: string) => sql.indexOf(`CREATE TABLE ${t} (`);
    expect(pos("orders")).toBeLessThan(pos("order_lines"));
    expect(pos("order_lines")).toBeLessThan(pos("line_notes"));
  });

  it("breaks cycles with ALTER TABLE, but keeps FKs inline for SQLite", () => {
    const a = makeTable("a", 0, 0, {
      columns: [
        makeColumn("id", "INT", { pk: true }),
        makeColumn("b_id", "INT", { nullable: true }),
      ],
    });
    const b = makeTable("b", 0, 0, {
      columns: [makeColumn("id", "INT", { pk: true }), makeColumn("a_id", "INT")],
    });
    const d = diagram(
      [a, b],
      [
        makeRelationship(b.id, a.id, { fromCol: b.columns[0].id, toCol: a.columns[1].id }),
        makeRelationship(a.id, b.id, { fromCol: a.columns[0].id, toCol: b.columns[1].id }),
      ],
    );
    const pg = toSql(d, "postgres");
    expect(pg).toContain(
      "ALTER TABLE a ADD CONSTRAINT fk_a_b_id FOREIGN KEY (b_id) REFERENCES b (id);",
    );
    expect(pg.indexOf("CREATE TABLE b")).toBeGreaterThan(pg.indexOf("CREATE TABLE a"));
    expect(pg.match(/FOREIGN KEY/g)).toHaveLength(2);

    const lite = toSql(d, "sqlite");
    expect(lite).not.toContain("ALTER TABLE");
    expect(lite).toContain("-- a, b reference each other in a cycle.");
    expect(lite).toContain("CONSTRAINT fk_a_b_id FOREIGN KEY (b_id) REFERENCES b (id)");
  });

  it("keeps self-references inline", () => {
    const emp = makeTable("employees", 0, 0, {
      columns: [
        makeColumn("id", "INT", { pk: true }),
        makeColumn("manager_id", "INT", { nullable: true }),
      ],
    });
    const d = diagram(
      [emp],
      [makeRelationship(emp.id, emp.id, { fromCol: emp.columns[0].id, toCol: emp.columns[1].id })],
    );
    const sql = toSql(d, "mysql");
    expect(sql).not.toContain("ALTER TABLE");
    expect(sql).toContain("REFERENCES employees (id)");
  });

  it("writes SERIAL per dialect, and SQLite's inline AUTOINCREMENT", () => {
    const t = makeTable("t", 0, 0, {
      columns: [
        makeColumn("id", "SERIAL", { pk: true }),
        makeColumn("flag", "BOOLEAN", { defaultValue: "true" }),
      ],
    });
    const d = diagram([t]);
    expect(toSql(d, "sqlite")).toContain("  id   INTEGER PRIMARY KEY AUTOINCREMENT,");
    expect(toSql(d, "sqlite")).not.toContain("PRIMARY KEY (id)");
    expect(toSql(d, "mysql")).toContain("id   INT AUTO_INCREMENT NOT NULL");
    const ms = toSql(d, "sqlserver");
    expect(ms).toContain("id   INT IDENTITY(1,1) NOT NULL");
    expect(ms).toContain("flag BIT               NOT NULL DEFAULT 1");
  });

  it("comments on lists, empty types, notes, N:M and missing FK columns", () => {
    const a = makeTable("authors", 0, 0, {
      note: "People who write",
      columns: [
        makeColumn("id", "INT", { pk: true }),
        makeColumn("tags", "TEXT[]", { multi: true, note: "comma separated" }),
        makeColumn("misc", ""),
      ],
    });
    const b = makeTable("books", 0, 0, { columns: [makeColumn("id", "INT", { pk: true })] });
    const d = diagram(
      [a, b],
      [
        makeRelationship(a.id, b.id, { type: "N:M", label: "write" }),
        makeRelationship(a.id, b.id, { label: "edits" }),
      ],
    );
    const pg = toSql(d, "postgres");
    expect(pg).toContain("tags TEXT[]       NOT NULL, -- holds a list: violates 1NF");
    expect(pg).toContain("misc VARCHAR(255) NOT NULL, -- TODO: choose a data type");
    expect(pg).toContain("COMMENT ON TABLE authors IS 'People who write';");
    expect(pg).toContain("COMMENT ON COLUMN authors.tags IS 'comma separated';");
    expect(pg).toContain("-- Many-to-many: authors (many) write books (many).");
    expect(pg).toContain('-- No foreign key for "authors (one) edits books (many)"');

    const my = toSql(d, "mysql");
    expect(my).toContain("JSON         NOT NULL COMMENT 'comma separated',");
    expect(my).toContain(") COMMENT='People who write';");
    const lite = toSql(d, "sqlite");
    expect(lite).toContain("-- People who write\nCREATE TABLE authors (");
    expect(lite).toContain("-- was TEXT[]; holds a list: violates 1NF; comma separated");
  });

  it("adds UNIQUE to a 1:1 foreign key and maps RESTRICT for SQL Server", () => {
    const u = makeTable("users", 0, 0, { columns: [makeColumn("id", "INT", { pk: true })] });
    const p = makeTable("profiles", 0, 0, {
      columns: [makeColumn("id", "INT", { pk: true }), makeColumn("user_id", "INT")],
    });
    const d = diagram(
      [p, u],
      [
        makeRelationship(u.id, p.id, {
          fromCol: u.columns[0].id,
          toCol: p.columns[1].id,
          type: "1:1",
          onDelete: "RESTRICT",
        }),
      ],
    );
    expect(toSql(d, "postgres")).toContain("user_id INT NOT NULL UNIQUE");
    expect(toSql(d, "postgres")).toContain("REFERENCES users (id) ON DELETE RESTRICT");
    const ms = toSql(d, "sqlserver");
    expect(ms).toContain(
      "REFERENCES users (id) -- ON DELETE RESTRICT: SQL Server has no RESTRICT; NO ACTION behaves the same",
    );
  });

  it("skips tables without columns and fills blank names", () => {
    const empty = makeTable("empty", 0, 0);
    const blank = makeTable("", 0, 0, { columns: [makeColumn("", "INT")] });
    const sql = toSql(diagram([empty, blank]), "postgres");
    expect(sql).toContain("-- empty has no columns yet, so no table was created.");
    expect(sql).toContain("CREATE TABLE table_2 (\n  column_1 INT NOT NULL\n);");
  });
});
