import { primaryKeyColumns, relSentence, type Column, type Diagram, type Table } from "@/lib/model";
import type { SqlDialect } from "@/lib/settings/types";
import { dependencyOrder, identFragment, resolveForeignKeys, type ForeignKey } from "../fk";
import { SQL_DIALECT_LABELS, actionFor, mapType, quoteIdent, quoteString } from "./dialects";

/** Collapse newlines so text can sit inside a `--` comment. */
function oneLine(s: string): string {
  return s.replace(/\s*[\r\n]+\s*/g, " ").trim();
}

interface Item {
  code: string;
  comments: string[];
}

/** `a, b` with each name quoted as needed. */
function colList(cols: Column[], dialect: SqlDialect): string {
  return cols.map((c) => quoteIdent(c.name, dialect)).join(", ");
}

function fkClause(fk: ForeignKey, dialect: SqlDialect): Item {
  const q = (s: string) => quoteIdent(s, dialect);
  let code =
    `CONSTRAINT ${fk.name} FOREIGN KEY (${colList(fk.childCols, dialect)}) ` +
    `REFERENCES ${q(fk.parent.name)} (${colList(fk.parentCols, dialect)})`;
  const comments: string[] = [];
  for (const [verb, action] of [
    ["DELETE", fk.onDelete],
    ["UPDATE", fk.onUpdate],
  ] as const) {
    const a = actionFor(action, dialect);
    if (a.sql) code += ` ON ${verb} ${a.sql}`;
    if (a.comment) comments.push(`ON ${verb} RESTRICT: ${a.comment}`);
  }
  return { code, comments };
}

function defaultFor(value: string, dialect: SqlDialect): string {
  const v = value.trim();
  if (dialect === "sqlserver") {
    if (/^true$/i.test(v)) return "1";
    if (/^false$/i.test(v)) return "0";
  }
  return v;
}

function names(d: Diagram): {
  table: (t: Table) => string;
  column: (c: Column, i: number) => string;
} {
  return {
    table: (t) => t.name.trim() || `table_${d.tables.indexOf(t) + 1}`,
    column: (c, i) => c.name.trim() || `column_${i + 1}`,
  };
}

/** CREATE TABLE script, dependency ordered, with PK/UNIQUE/NOT NULL/FK constraints. */
export function toSql(d: Diagram, dialect: SqlDialect): string {
  // Work on a copy with blank names filled in so every identifier is valid.
  const nm = names(d);
  const diagram: Diagram = {
    ...d,
    tables: d.tables.map((t) => ({
      ...t,
      name: nm.table(t),
      columns: t.columns.map((c, i) => ({ ...c, name: nm.column(c, i) })),
    })),
  };
  const q = (s: string) => quoteIdent(s, dialect);
  const { fks, manyToMany, unresolved } = resolveForeignKeys(diagram);
  const { order, deferred, cyclic } = dependencyOrder(diagram, fks);
  const deferredSet = new Set(dialect === "sqlite" ? [] : deferred);
  const oneToOneCols = new Set(
    fks.filter((fk) => fk.oneToOne && fk.childCols.length === 1).map((fk) => fk.childCols[0].id),
  );

  const out: string[] = [];
  out.push(`-- ${oneLine(d.name) || "Untitled diagram"}`);
  out.push(`-- Generated by ERD Studio for ${SQL_DIALECT_LABELS[dialect]}`);
  if (dialect === "sqlite") out.push("", "PRAGMA foreign_keys = ON;");
  if (dialect === "sqlite" && cyclic.length) {
    out.push(
      "",
      `-- ${cyclic.map((t) => t.name).join(", ")} reference each other in a cycle. SQLite can't add`,
      "-- foreign keys later, so they stay inline; it only checks them when rows change.",
    );
  }

  for (const t of order) {
    out.push("");
    if (!t.columns.length) {
      out.push(`-- ${oneLine(t.name)} has no columns yet, so no table was created.`);
      continue;
    }
    if (t.note && dialect !== "postgres" && dialect !== "mysql") {
      for (const line of t.note.split(/\r?\n/)) if (line.trim()) out.push(`-- ${line.trim()}`);
    }

    const pk = primaryKeyColumns(t);
    const rows: { parts: [string, string, string]; comments: string[] }[] = [];
    let inlinePk = false;
    for (const c of t.columns) {
      const mapped = mapType(c.type, dialect);
      const comments: string[] = [];
      if (mapped.comment) comments.push(mapped.comment);
      const attrs: string[] = [];
      if (mapped.autoIncrement && c.pk && pk.length === 1) {
        attrs.push("PRIMARY KEY AUTOINCREMENT");
        inlinePk = true;
      } else if (!c.nullable || c.pk) attrs.push("NOT NULL");
      else if (dialect === "sqlserver") attrs.push("NULL");
      if (c.defaultValue.trim()) attrs.push(`DEFAULT ${defaultFor(c.defaultValue, dialect)}`);
      const soloPk = c.pk && pk.length === 1;
      if (!soloPk && (c.unique || oneToOneCols.has(c.id))) attrs.push("UNIQUE");
      if (c.note && dialect === "mysql")
        attrs.push(`COMMENT ${quoteString(oneLine(c.note), dialect)}`);
      if (c.multi) comments.push("holds a list: violates 1NF");
      if (c.note && dialect !== "mysql" && dialect !== "postgres") comments.push(oneLine(c.note));
      rows.push({ parts: [q(c.name), mapped.type, attrs.join(" ")], comments });
    }
    const w0 = Math.max(...rows.map((r) => r.parts[0].length));
    const w1 = Math.max(...rows.map((r) => r.parts[1].length));
    const items: Item[] = rows.map((r) => ({
      code: `${r.parts[0].padEnd(w0)} ${r.parts[1].padEnd(w1)} ${r.parts[2]}`.trimEnd(),
      comments: r.comments,
    }));
    if (pk.length && !inlinePk)
      items.push({ code: `PRIMARY KEY (${colList(pk, dialect)})`, comments: [] });
    for (const fk of fks) {
      if (fk.child.id === t.id && !deferredSet.has(fk)) items.push(fkClause(fk, dialect));
    }

    out.push(`CREATE TABLE ${q(t.name)} (`);
    items.forEach((it, i) => {
      const comma = i < items.length - 1 ? "," : "";
      const comment = it.comments.length ? ` -- ${it.comments.join("; ")}` : "";
      out.push(`  ${it.code}${comma}${comment}`);
    });
    const tableComment =
      dialect === "mysql" && t.note ? ` COMMENT=${quoteString(oneLine(t.note), dialect)}` : "";
    out.push(`)${tableComment};`);

    if (dialect === "postgres") {
      if (t.note) out.push(`COMMENT ON TABLE ${q(t.name)} IS ${quoteString(t.note, dialect)};`);
      for (const c of t.columns) {
        if (c.note) {
          out.push(
            `COMMENT ON COLUMN ${q(t.name)}.${q(c.name)} IS ${quoteString(c.note, dialect)};`,
          );
        }
      }
    }
  }

  if (deferredSet.size) {
    out.push("", "-- These tables reference each other in a cycle, so these keys are added last.");
    for (const fk of deferred) {
      const clause = fkClause(fk, dialect);
      const comment = clause.comments.length ? ` -- ${clause.comments.join("; ")}` : "";
      out.push(`ALTER TABLE ${q(fk.child.name)} ADD ${clause.code};${comment}`);
    }
  }

  const notes: string[] = [];
  for (const r of manyToMany) {
    const a = diagram.tables.find((t) => t.id === r.from)!;
    const b = diagram.tables.find((t) => t.id === r.to)!;
    notes.push(
      `-- Many-to-many: ${oneLine(relSentence(diagram, r))}. Add a junction table such as`,
      `--   ${identFragment(a.name)}_${identFragment(b.name)} with a foreign key to each side.`,
    );
  }
  for (const { rel, reason } of unresolved) {
    const sentence = oneLine(relSentence(diagram, rel));
    const child = diagram.tables.find((t) => t.id === rel.to)!;
    const parent = diagram.tables.find((t) => t.id === rel.from)!;
    notes.push(
      reason === "no-child-column"
        ? `-- No foreign key for "${sentence}": choose the column on ${oneLine(child.name)} that holds the key.`
        : `-- No foreign key for "${sentence}": choose the column it references on ${oneLine(parent.name)}.`,
    );
  }
  if (notes.length) out.push("", ...notes);
  return out.join("\n") + "\n";
}
